### ISSUE TITLE
Recipe Rails Capstone Project Setup

### ISSUE THREAD

**Issue by codewanderlust** [RoyJumah/recipe-app#9]
> Hi, for this project there are two group members;
- @RoyJumah 
- @Hassaanjbaig-code 

- Here is the [link](https://github.com/users/RoyJumah/projects/4) to the project that we just set up

**Comment by danmainah** [comment]
Hi @RoyJumah and @Hassaanjbaig-code , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good project design
✔️  Good Issue Description with the correct info


# Required Changes ♻️

- [ ] @team great work on your cards however two project requirements are not in any of the cards,  `Should display a toggle button that allows for a recipe to be made public or private. Write unit and integration tests` kindly ensure to include these requirements in your kanban board.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by codewanderlust** [comment]
- We have made the suggested changes

**Comment by Olamarx** [comment]
> > Hi, for this project there are two group members;
> 
> * @RoyJumah
> * @Hassaanjbaig-code
> * Here is the [link](https://github.com/users/RoyJumah/projects/4) to the project that we just set up

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/a9imQoghMq5IQ/giphy.gif"/>
## Highlights
- Kanban Setup ✔️
- Equal distribution ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
